import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import 'models/book.dart';
import 'firebase_options.dart'; // generated by flutterfire CLI


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const BookApp());
}


class BookApp extends StatelessWidget {
  const BookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Book App',
      home: const BookFirebaseDemo(),
    );
  }
}

class BookFirebaseDemo extends StatefulWidget {

  const BookFirebaseDemo({super.key});

  final String appTitle = 'Book DB';

  @override
  State<BookFirebaseDemo> createState() => _BookFirebaseDemoState();
}

class _BookFirebaseDemoState extends State<BookFirebaseDemo> {

  TextEditingController bookNameController = TextEditingController();
  TextEditingController bookAuthorController = TextEditingController();

  bool isEditing = false;
  bool textFieldVisibility = false;

  String firestoreCollectionName = "Books";
  Book? currentBook;

  Stream<QuerySnapshot> getAllBooks() {
    return FirebaseFirestore.instance.collection(firestoreCollectionName).snapshots();
  }

  void clearTextFields() {
    bookNameController.clear();
    bookAuthorController.clear();
  }

  Future<void> addBook() async {
    final bookName = bookNameController.text.trim();
    final authorName = bookAuthorController.text.trim();

    if (bookName.isEmpty || authorName.isEmpty) {
      debugPrint('Book name and author name cannot be empty');
      return;
    }

    Book book = Book(bookName: bookName, authorName: authorName);

    try {
      await FirebaseFirestore.instance
          .collection(firestoreCollectionName)
          .doc()
          .set(book.toJson());
      clearTextFields();
    } catch (e) {
      debugPrint('Error adding book: $e');
    }
  }

  Future<void> updateBook(
  Book book,
  String bookName,
  String authorName,
) async {
  final trimmedBookName = bookName.trim();
  final trimmedAuthorName = authorName.trim();

  if (trimmedBookName.isEmpty || trimmedAuthorName.isEmpty) {
    debugPrint('Book name and author name cannot be empty');
    return;
  }

  try {
    await FirebaseFirestore.instance
        .collection(firestoreCollectionName)
        .doc(book.documentReference!.id)
        .update({
          'bookName': trimmedBookName,
          'authorName': trimmedAuthorName,
        });
    clearTextFields();
  } catch (e) {
    debugPrint('Error updating book: $e');
  }
}

Future<void> updateIfEditing() async {
  if (isEditing) {
    await updateBook(
      currentBook!,
      bookNameController.text,
      bookAuthorController.text,
    );
  } else {
    await addBook();
  }

  setState(() {
    isEditing = false;
    textFieldVisibility = false;
    currentBook = null;
  });
}


  Future<void> deleteBook(Book book) async {
    if (book.documentReference == null) {
      debugPrint('Cannot delete: document reference is null');
      return;
    }
    try {
      await FirebaseFirestore.instance
          .collection(firestoreCollectionName)
          .doc(book.documentReference!.id)
          .delete();
    } catch (e) {
      debugPrint('Error deleting book: $e');
    }
  }



Widget buildbody(BuildContext context) {
  return StreamBuilder<QuerySnapshot>(
    stream: getAllBooks(),
    builder: (context, snapshot) {
      if (snapshot.hasError) {
        return Text('Error: ${snapshot.error}');
      }

      if (snapshot.hasData) {
        debugPrint(
            "Data received: ${snapshot.data!.docs.length} books");
        return buildList(context, snapshot.data!.docs);
      }

      return const Center(
        child: CircularProgressIndicator(),
      );
    },
  );
}


Widget buildList(BuildContext context, List<DocumentSnapshot> snapshot) {
    return ListView(
      children: snapshot.map((data) => listItemBuild(context, data)).toList(),
    );
  }

  Widget listItemBuild(BuildContext context, DocumentSnapshot data) {
    final book = Book.fromSnapshot(data);

    return Padding(
      key: ValueKey(book.bookName ?? DateTime.now().toString()),
      padding: EdgeInsets.symmetric(vertical: 5, horizontal: 1),
      child: Container(
          decoration: BoxDecoration(
            border: Border.all(color: Colors.blueAccent),
            borderRadius: BorderRadius.circular(4),
          ),
          child: ListTile(
            title: Column(
              children: <Widget>[
                Row(
                  children:<Widget>[
                    Icon(Icons.book, color: Colors.blueAccent),
                    Text(book.bookName ?? 'Unknown Book')
                  ]
                ),
                Divider(),
                Row(
                  children:<Widget>[
                    Icon(Icons.person, color: Colors.blueAccent),
                    Text(book.authorName ?? 'Unknown Author')
                  ]
                ),
              ],
            ),
            trailing: IconButton(
              icon: Icon (Icons.delete, color: Colors.redAccent),
              onPressed: () async {
                await deleteBook(book);
              },

            ),
            onTap: (){
              setUpdateUI(book);
            }
          )
      ),
    );
  }


void setUpdateUI(Book book) {
    bookNameController.text = book.bookName ?? '';
    bookAuthorController.text = book.authorName ?? '';

    setState(() {
      isEditing = true;
      textFieldVisibility = true;
      currentBook = book;
    });
  }

Widget button(){
  return SizedBox(
    width: double.infinity,
    child: ElevatedButton(
      onPressed: () async {
        if (isEditing) {
          await updateIfEditing();
        } else {
          await addBook();
        }

        setState(() {
          textFieldVisibility = false;
          isEditing = false;
          currentBook = null;
        });
      },
      child: Text(isEditing ? 'Update Book' : 'Add Book'),
    ),
  );
}

@override
Widget build(BuildContext context) {
  return Scaffold(
    resizeToAvoidBottomInset: false,
    appBar: AppBar(
      title: Text(widget.appTitle),
      actions: <Widget>[
        IconButton(
          icon: Icon(Icons.add),
          onPressed: () {
            setState(() {
              textFieldVisibility = !textFieldVisibility;
              if (!textFieldVisibility) {
                clearTextFields();
                isEditing = false;
                currentBook = null;
              }
            });
          },
        ),
      ],
    ),
    body: Container(
      padding: EdgeInsets.all(19),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.start,
        children: <Widget>[
          textFieldVisibility
              ? Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: <Widget>[
                    TextFormField(
                      controller: bookNameController,
                      decoration: InputDecoration(
                        labelText: 'Book Name',
                        hintText: 'Enter book name',
                      ),
                    ),
                    TextFormField(
                      controller: bookAuthorController,
                      decoration: InputDecoration(
                        labelText: 'Author Name',
                        hintText: 'Enter author name',
                      ),
                    ),
                  ],
                )
              : SizedBox(height: 10),

          button(),

          SizedBox(height: 20),

          Text(
            "BOOKS",
            style: TextStyle(
              fontSize: 24,
              fontWeight: FontWeight.w800,
            ),
          ),
          SizedBox(
            height: 20
          ),
          Flexible(child:   buildbody(context),
          ),
        ],
      ),
    ),
  );
}


}
